language: swift
osx_image: xcode10.1
xcode_sdk: iphonesimulator12.1
node_js:
- '8'
branches:
  only:
  - devel
  - ux-loop
  - master
cache:
  bundler: true
    
before_install:
- openssl aes-256-cbc -K $encrypted_2be08fd24366_key -iv $encrypted_2be08fd24366_iv -in .travis/secret.tar.enc -out secret.tar -d
- tar xvf secret.tar
- chmod +x ssh-deploy.sh
- ./ssh-deploy.sh
install:
- fastlane add_plugin latest_hockey_build_number
- fastlane add_plugin sentry
- brew install getsentry/tools/sentry-cli
script:
- |
    if [ $TRAVIS_BRANCH == "master" ]; then
      fastlane ios betatravis
    else
      fastlane ios developtravis
    fi
after_success: 
