language: swift
osx_image: xcode10
xcode_sdk: iphonesimulator12.0
node_js:
- '8'
branches:
  only:
  - devel
  - ux-loop
  - master
cache:
  bundler: true
  cocoapods: true
  directories:
  - node_modules # NPM packages
    
before_install:
- openssl aes-256-cbc -K $encrypted_2be08fd24366_key -iv $encrypted_2be08fd24366_iv -in .travis/ssh-deploy.sh.enc -out ssh-deploy.sh -d
- chmod +x ssh-deploy.sh
- ./ssh-deploy.sh
- gem install fastlane
install:
- fastlane add_plugin latest_hockey_build_number
script:
- |
    if [ $TRAVIS_BRANCH == "master" ]; then
      fastlane ios betatravis
    else
      fastlane ios developtravis
    fi
after_success: 
