# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

git_pull
Dir.chdir("..") do
  sh "npm install"
end

platform :ios do
  desc "Push a new beta build to Hockeyapp"
  lane :beta do
    version_number = latest_hockey_build_number(
      api_token: "ea44d63ef04b42d8898c686a5744346c"
    ).to_i
    increment_build_number(
      xcodeproj: "Bitmark.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false,
      adhoc: true
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "Bitmark.xcworkspace", 
      scheme: "Bitmark",
      include_bitcode: false
    )
    hockey(
      api_token: "ea44d63ef04b42d8898c686a5744346c"
    )
  end
  lane :enterprise do
    version_number = latest_hockey_build_number(
      api_token: "58599adb15fb45e588c850af7b79a432"
    ).to_i
    increment_build_number(
      xcodeproj: "Bitmark.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "Bitmark.xcworkspace", 
      scheme: "Bitmark beta",
      include_bitcode: false
    )
    hockey(
      api_token: "58599adb15fb45e588c850af7b79a432"
      )
  end
  lane :development do
    version_number = latest_hockey_build_number(
      api_token: "b6fb005cafb04a33a812013c13384480"
    ).to_i
    increment_build_number(
      xcodeproj: "Bitmark.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "Bitmark.xcworkspace", 
      scheme: "Bitmark dev",
      include_bitcode: false
    )
    hockey(
      api_token: "b6fb005cafb04a33a812013c13384480"
      )
  end
end
