platform :ios, '11.0'

def pods
    # Pods for Bitmark
    
    pod 'BitmarkSDK'
    pod 'KeychainAccess'
    pod 'iCloudDocumentSync'
    
end

target 'Bitmark Registry' do
  use_frameworks!

  pods

  target 'BitmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Bitmark Registry beta' do
    use_frameworks!
    
    pods
    
end

target 'Bitmark Registry dev' do
    use_frameworks!
    
    pods
    
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.2'      end
  end
end
