# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

reset_git_repo(
  force: true,
  skip_clean: true
)
git_pull
sh "npm install"

platform :ios do
  desc "Push a new beta build to Hockeyapp"
  lane :prepare_appstore do
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    ).to_i
    increment_build_number(
      xcodeproj: "ios/Bitmark Registry.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false,
      adhoc: true
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/Bitmark.xcworkspace", 
      scheme: "Bitmark Registry",
      include_bitcode: false
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY']
    )
  end
  lane :beta do
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    ).to_i
    increment_build_number(
      xcodeproj: "ios/Bitmark Registry.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/Bitmark.xcworkspace", 
      scheme: "Bitmark Registry beta",
      include_bitcode: false
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY']
      )
  end
  lane :alpha do
    version_number = latest_hockey_build_number(
      api_token: ENV['HOCKEYAPP_KEY']
    ).to_i
    increment_build_number(
      xcodeproj: "ios/Bitmark Registry.xcodeproj",
      build_number: (version_number + 1).to_i
    )
    cert
    sigh(
      force: false
    )
    build_app(
      export_options: {iCloudContainerEnvironment: 'Production'},
      workspace: "ios/Bitmark.xcworkspace", 
      scheme: "Bitmark Registry dev",
      include_bitcode: false
    )
    hockey(
      api_token: ENV['HOCKEYAPP_KEY']
      )
  end
end