platform :ios, '10.0'

def pods
    # Pods for Bitmark
    
    pod 'BitmarkSDK', :git => 'https://github.com/bitmark-inc/bitmark-sdk-swift.git'
    pod 'KeychainAccess'
    
end

target 'Bitmark Registry' do
  use_frameworks!

  pods

  target 'BitmarkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Bitmark Registry dev' do
    use_frameworks!
    
    pods
    pod 'HockeySDK'
    
end

target 'Bitmark Registry dev e2e' do
    use_frameworks!
    
    pods
    pod 'HockeySDK'
    
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.1'      end
  end
end
